---
- name: Install the YB-Voyager on Centos 
  hosts: local
  become: yes
  
  tasks:
    - name: Install the wget 
      ansible.builtin.dnf: 
        name: wget 
        state: latest
      register: wget 

    - name: print the wget 
      ansible.builtin.debug:
        msg: "{{ wget }}"

    - name: Upgrade all packages
      ansible.builtin.dnf: 
        name: "*"
        state: latest
      register: update
    
    - name: print the update 
      ansible.builtin.debug: 
        msg: "{{update}}"

    - name: Install the java-17 version 
      ansible.builtin.dnf: 
        name: java >= 17
        state: present
      register: java

    - name: print the java 
      ansible.builtin.debug: 
        msg: "{{ java }}"

    - name: Upgrade All packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: update_1

    - name: Print the update_1
      ansible.builtin.debug:
        msg: "{{ update_1 }}"
    
    - name: Install the yugabyte yum repository using the following command
      ansible.builtin.dnf: 
        name: 'https://downloads.yugabyte.com/repos/reporpms/yb-yum-repo-1.1-0.noarch.rpm -y'
        state: present
      register: yum_repo

    - name: Print yum_repo
      ansible.builtin.debug:
        msg: "{{ yum_repo }}"


    