---
- name: Install the YB-Voyager on Centos 
  hosts: local
  become: yes
  
  tasks:
    - name: Install the wget 
      ansible.builtin.dnf: 
        name: wget 
        state: latest
      register: wget 

    - name: print the wget 
      ansible.builtin.debug:
        msg: "{{ wget }}"

    - name: Upgrade all packages
      ansible.builtin.dnf: 
        name: "*"
        state: latest
      register: update
    
    - name: print the update 
      ansible.builtin.debug: 
        msg: "{{update}}"
    