---
- name: Install Yugabyte Anywhere
  hosts: all
  become: yes
  vars:
    yba_version: "2024.2.2.2-b2"
    yba_tar_file: "yba_installer_full-{{ yba_version }}-linux-x86_64.tar.gz"
    yba_url: "https://downloads.yugabyte.com/releases/2024.2.2.2/{{ yba_tar_file }}"
    yba_dir: "yba_installer_full-{{ yba_version }}"
    yba_install_dir: "/opt/yba-ctl"
    license_secret_name: "yba_lic"
    tmp_license_file: "/tmp/yba.lic"
    final_license_path: "{{ yba_install_dir }}/yba.lic"

  tasks:

    - name: Install wget, tar, python3.11
      ansible.builtin.yum: 
        name:
          - wget 
          - python3.11
          - tar 
        state: present

    - name: Download YBA tarball
      ansible.builtin.get_url:
        url: "{{ yba_url }}"
        dest: "/tmp/{{ yba_tar_file }}"
        mode: '0644'

    - name: Extract YBA tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ yba_tar_file }}"
        dest: /tmp
        remote_src: yes

    - name: Fetch the YBA license from the Secrete Manager
      ansible.builtin.shell: |
        gcloud secrets versions access latest --secret='yba_lic'
      register: secrete_value

    - name: Check if license was fetched successfully 
      ansible.builtin.debug: 
        msg: "{{ secrete_value }}"
      


    