---
##
- name: Update the system package 
  ansible.builtin.yum: 
    name: Update the machine 
    state: latest
    register: Update_Output

- name: Print the update_Output
  ansible.builtin.debug:
    msg: "{{Update_Output}}"
    