---
# vars file for ybdb
yugabyte_version: "2.25.0.0"
yugabyte_build: "b489"
yugabyte_tarball: "yugabyte-{{ yugabyte_version }}-{{ yugabyte_build }}-linux-x86_64.tar.gz"
yugabyte_dir: "yugabyte-{{ yugabyte_version }}"
start_time: "{{ lookup('pipe', 'date +%s') }}"